name: flask-rq-example
dependencies:
- ca-certificates=2016.8.2=3
- certifi=2016.8.2=py35_0
- click=6.6=py35_0
- flask=0.11.1=py35_0
- flask-wtf=0.12=py35_0
- itsdangerous=0.24=py35_0
- jinja2=2.8=py35_1
- markupsafe=0.23=py35_2
- openssl=1.0.2h=2
- pip=8.1.2=py35_0
- python=3.5.2=2
- readline=6.2=2
- setuptools=25.1.6=py35_0
- sqlite=3.13.0=1
- tk=8.5.19=0
- werkzeug=0.11.10=py35_0
- wheel=0.29.0=py35_0
- wtforms=2.1=py35_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - dominate==2.2.1
  - flask-bootstrap==3.3.6.0
  - flask-script==2.0.5
  - redis==2.10.5
  - rq==0.6.0
  - visitor==0.1.3

